name: Install NPM and Show Version
on: [push, workflow_dispatch]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Get code by Checkout
        uses: actions/checkout@v3
    
      - name: Get NPM Version 18
        uses: actions/setup-node@v3
        with:
         node-version: 18
        
      - name: Print Version
        run: |
          chmod +x npm-version.sh
          #./npm-version.sh
          #npm version
          echo  "Completed Running the Version"
  
  Context-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context Info
        run: echo "${{ toJSON(github) }}"
  
